global:
  scrape_interval: 15s  # How often to scrape targets
  evaluation_interval: 15s  # How often to evaluate rules

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['host.docker.internal:9187']  # PostgreSQL Exporter

  - job_name: 'redis'
    static_configs:
      - targets: ['host.docker.internal:9121']  # Redis Exporter

  - job_name: 'nginx'
    static_configs:
      - targets: ['host.docker.internal:9113']  # Nginx Prometheus Exporter

  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']  # Monitor itself
