"""qa model index gin

Revision ID: 03e055d5be3f
Revises: d37ef0ec1f0a
Create Date: 2025-04-02 16:00:35.112227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03e055d5be3f'
down_revision: Union[str, None] = 'd37ef0ec1f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qa_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('qa_history_input_text_gin_idx', 'qa_history', [sa.literal_column("to_tsvector('simple', input_text)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('qa_history_input_text_gin_idx', table_name='qa_history', postgresql_using='gin')
    op.alter_column('qa_history', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
