"""is_active all models

Revision ID: 40ed10af75e2
Revises: 03e055d5be3f
Create Date: 2025-04-04 18:15:36.866248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ed10af75e2'
down_revision: Union[str, None] = '03e055d5be3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('collection', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('product', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('product', sa.Column('brand_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product', 'brand', ['brand_id'], ['brand_id'], ondelete='CASCADE')
    op.add_column('supplier', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier', 'is_active')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'brand_id')
    op.drop_column('product', 'is_active')
    op.drop_column('collection', 'is_active')
    op.drop_column('brand', 'is_active')
    # ### end Alembic commands ###
